[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.12",
    "bcrypt>=4.3.0",
    "fastapi>=0.115.12",
    "fastmcp>=2.8.0",
    "jira>=3.8.0",
    "pandas>=2.3.0",
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
    "weaviate-client==3.*",
]
